PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/09778c38b1d63f8a8fd02441129bc721c2a33aa9

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/904a602c74dc08a100b5c2bd490807de19e73e10) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX/compare/904a602c74dc08a100b5c2bd490807de19e73e10...09778c38b1d63f8a8fd02441129bc721c2a33aa9

09778c38b1 (HEAD, origin/master) rptun: fix rptun rpmsg_unregister_callback fault
4e460cd440 arch/stm32: Fix nxstyle errors
324d3a89ed Revert "arch: cxd56xx: Fix the pause handler for SMP"
16436a7fb6 Revert "arch: armv7-a: Fix the pause handler for SMP"
3ba840aa27 Revert "arch: lc823450: Fix the pause handler for SMP"
37dad5dd04 Revert "arch: k210: Fix the pause handler for SMP"
b237748f50 Revert "arch: xtensa: Fix the pause handler for SMP"
6b767c6856 Revert "Update TODO regarding SMP"
c91939b5c0 Documentation: improve debugging section
9f6a43d0b0 libs: audio: libsamplerate: drop local patches

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/72d9b34fb13958b5798a180f815257446f57f597

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf) in current PX4/master (5e855c67477fe08517297a38e718ed1102536cf6)
https://github.com/PX4/NuttX-apps/compare/909eff540d8004371d5838b9c0764cc753d665cf...72d9b34fb13958b5798a180f815257446f57f597

72d9b34f (HEAD -> master, origin/master) netutils/tftpc/tftpc_put.c: Fix syslog formats
5a4bf6b3 netutils/tftpc/tftpc_get.c: Fix a syslog format
eeded9da netutils/ntpclient/ntpclient.c: Fix syslog formats
13424fc4 netutils/ftpc/ftpc_putfile.c: Fix syslog formats
2a3f2ea8 netutils/ftpc/ftpc_putfile.c: Appease nxstyle
7b3ccfa9 netutils/ftpc/ftpc_getfile.c: Fix a syslog format
f83caca9 netutils/ftpc/ftpc_getfile.c: Appease nxstyle
24b6f919 examples/mld: Fix undefined reference to `mld_catfile'
a4ae1592 examples/i2schar: Fix the compile error
736a21f0 examples/chrono: Rename button_daemon to chrono_daemon